### ISSUE TITLE
Missing yaml dependency for python package

### ISSUE THREAD

**Issue by bssb** [beancount/beancount2ledger#41]
After installing beancount2ledger using `pip install beancount2ledger` on Windows, I'm getting this error:
```
PS C:\Users\brrts\git\ledger> beancount2ledger
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\brrts\scoop\apps\python\current\Scripts\beancount2ledger.exe\__main__.py", line 4, in <module>
  File "C:\Users\brrts\scoop\apps\python\current\Lib\site-packages\beancount2ledger\cli.py", line 16, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```
Running `pip install pyyaml` resolves the issue.

**Comment by tbm** [comment]
Thanks for reporting this!  If you find other issues, please open new issues.  I need to work on beancount2ledger again soon and fix some outstanding issues.
